# Site settings
title: Tech talk – my experiments with technology...
email: asinghal79@gmail.com
description: Aishwarya is an experienced technology leader with a proven track record of delivering results over almost 2 decades. This site has his observations from different experiments.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://asinghal.github.io" # the base hostname & protocol for your site
twitter_username: asinghal79
github_username:  asinghal
linkedin_url: "https://www.linkedin.com/in/aishwaryasinghal/"
gems:
  - jemoji
# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge